image: node:latest

before_script:
  - echo "Job `$CI_JOB_NAME` started."

after_script:
  - echo "Job `$CI_JOB_NAME` ended."

stages:
  - build
  - staging
  - production

build:
  type: build
  script:
    - npm install
    - npm run build
  except:
    - master
    - develop

deploy-staging:
  image: ruby:2.5
  type: deploy
  stage: staging
  only:
    - develop
  environment:
    name: staging
    url: https://staging-challengetestcode.herokuapp.com/
  script:
    - apt-get update -qy
    - apt-get install -y ruby ruby-dev rubygems-integration
    - gem install dpl
    - dpl --provider=heroku --app=staging-challengetestcode --api-key=$HEROKU_API_KEY

deploy-production:
  image: ruby:2.5
  type: deploy
  stage: production
  environment:
    name: production
    url: https://challengetestcode.herokuapp.com/
  script:
    - apt-get update -qy
    - apt-get install -y ruby ruby-dev rubygems-integration
    - gem install dpl
    - dpl --provider=heroku --app=challengetestcode --api-key=$HEROKU_API_KEY
  only:
    - master
